/**
 * Lowering to JavaScript ES modules.
 *
 * docs/architecture/compiler.md requires lowering to make evaluation order,
 * branching and runtime checks explicit, to use hygienic names, and to produce
 * deterministic output for the same source and compiler version.
 *
 * The two things this file must not get wrong:
 *
 *   1. Evaluation order. An `if` used as a value becomes a statement-level
 *      temporary rather than an IIFE, because an IIFE would capture a `return`
 *      that belongs to the enclosing Koda function. When a later operand needs
 *      that hoisting, earlier operands are bound to temporaries first so they
 *      still evaluate left to right, exactly once.
 *
 *   2. Numbers. Int is emitted as BigInt and every Int operation goes through
 *      the runtime's checked helpers with its source location, because ADR 0008
 *      requires checked signed 64-bit arithmetic with source-located faults on
 *      every backend. Float maps to an ordinary JavaScript number, which is
 *      binary64 with the rounding, overflow and NaN behaviour ADR 0008 accepts.
 *
 * The Int representation itself is a Q08 question that is still unresolved;
 * see docs/implementation/slice-0.md.
 */
import type { SourceFile, Span } from "../source/source.js";
import type {
  FunctionSymbol,
  IRBlock,
  IRExpression,
  IRFunction,
  IRMatch,
  IRModule,
  IRStatement,
  LocalSymbol,
} from "../ir/ir.js";

/** The namespace the generated module binds the runtime to. */
const RUNTIME = "$k";

const INT_HELPERS = {
  "+": "iadd",
  "-": "isub",
  "*": "imul",
  "/": "idiv",
  "%": "irem",
} as const;

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * Koda identifiers are ASCII `[A-Za-z_][A-Za-z0-9_]*`, so a single `k_` prefix
 * is injective and can never collide with `$k` or a generated temporary.
 */
function jsName(symbol: LocalSymbol | FunctionSymbol): string {
  return `k_${symbol.name}`;
}

/**
 * Record fields and payload values become object properties under the same
 * `k_` prefix, which keeps a Koda field called `__proto__` or `constructor`
 * from meaning anything to JavaScript.
 *
 * The layout itself is a Q08 question that is still unresolved; see
 * docs/implementation/slice-1a.md.
 */
function fieldKey(name: string): string {
  return `k_${name}`;
}

/**
 * Discriminates an enum value. A Koda identifier cannot contain `$`, so this
 * can never collide with a payload field.
 */
const TAG_KEY = "$tag";

function floatLiteral(value: number): string {
  if (Number.isNaN(value)) return "NaN";
  if (value === Number.POSITIVE_INFINITY) return "Infinity";
  if (value === Number.NEGATIVE_INFINITY) return "-Infinity";
  if (Object.is(value, -0)) return "-0";
  return String(value);
}

export interface EmittedModule {
  /** The ES module holding the compiled functions. */
  readonly moduleSource: string;
  /** The launcher that calls `main`; null when the module has no entry. */
  readonly launcherSource: string | null;
}

class Emitter {
  private readonly file: SourceFile;
  private readonly lines: string[] = [];
  private indent = 0;
  private temporaries = 0;

  constructor(file: SourceFile) {
    this.file = file;
  }

  private push(line: string): void {
    this.lines.push(line === "" ? "" : `${"  ".repeat(this.indent)}${line}`);
  }

  private freshTemp(): string {
    const name = `$t${this.temporaries}`;
    this.temporaries += 1;
    return name;
  }

  private bindTemp(expression: string): string {
    const name = this.freshTemp();
    this.push(`const ${name} = ${expression};`);
    return name;
  }

  /** `"src/main.ko:3:9"`, used to locate a checked arithmetic fault. */
  private location(span: Span): string {
    const position = this.file.positionOf(span.start);
    return JSON.stringify(`${span.file}:${position.line}:${position.column}`);
  }

  // ------------------------------------------------------------------ module

  emitModule(module: IRModule): string {
    this.push("// Generated by the Koda compiler. Do not edit.");
    this.push(`import * as ${RUNTIME} from "./koda-runtime.mjs";`);
    this.push("");

    for (const fn of module.functions) {
      this.temporaries = 0;
      this.emitFunction(fn);
      this.push("");
    }

    const exported = module.functions
      .filter((fn) => fn.symbol.origin.kind === "declared" && fn.symbol.origin.exported)
      .map((fn) => `${jsName(fn.symbol)} as ${fn.symbol.name}`);
    if (exported.length > 0) this.push(`export { ${exported.join(", ")} };`);

    return `${this.lines.join("\n").replace(/\n+$/, "")}\n`;
  }

  private emitFunction(fn: IRFunction): void {
    const parameters = fn.symbol.parameters.map((parameter) => jsName(parameter)).join(", ");
    this.push(`function ${jsName(fn.symbol)}(${parameters}) {`);
    this.indent += 1;
    this.emitBlockStatements(fn.body);
    if (fn.body.tail) {
      if (fn.symbol.returnType.kind === "Unit" || fn.body.tail.type.kind === "Never") {
        this.emitForEffect(fn.body.tail);
      } else {
        this.push(`return ${this.lowerValue(fn.body.tail)};`);
      }
    }
    this.indent -= 1;
    this.push("}");
  }

  private emitBlockStatements(block: IRBlock): void {
    for (const statement of block.statements) this.emitStatement(statement);
  }

  private emitStatement(statement: IRStatement): void {
    switch (statement.kind) {
      case "declare": {
        const value = this.lowerValue(statement.value);
        const keyword = statement.symbol.mutable ? "let" : "const";
        this.push(`${keyword} ${jsName(statement.symbol)} = ${value};`);
        return;
      }
      case "assign": {
        const value = this.lowerValue(statement.value);
        this.push(`${jsName(statement.symbol)} = ${value};`);
        return;
      }
      case "return": {
        if (!statement.value) {
          this.push("return;");
          return;
        }
        this.push(`return ${this.lowerValue(statement.value)};`);
        return;
      }
      case "eval":
        this.emitForEffect(statement.value);
    }
  }

  /** Evaluates an expression for its effects, without building a value. */
  private emitForEffect(expression: IRExpression): void {
    if (expression.kind === "match") {
      this.lowerMatch(expression, null);
      return;
    }
    if (expression.kind === "if") {
      const condition = this.lowerValue(expression.condition);
      this.push(`if (${condition}) {`);
      this.indent += 1;
      this.emitBranchForEffect(expression.then);
      this.indent -= 1;
      if (expression.otherwise) {
        this.push("} else {");
        this.indent += 1;
        this.emitBranchForEffect(expression.otherwise);
        this.indent -= 1;
      }
      this.push("}");
      return;
    }
    const value = this.lowerValue(expression);
    if (IDENTIFIER.test(value)) return;
    this.push(`${value};`);
  }

  private emitBranchForEffect(block: IRBlock): void {
    this.emitBlockStatements(block);
    if (block.tail) this.emitForEffect(block.tail);
  }

  private emitBranchInto(block: IRBlock, target: string): void {
    this.emitBlockStatements(block);
    if (!block.tail) return;
    // A branch that always returns produces no value to assign.
    if (block.tail.type.kind === "Never") {
      this.emitForEffect(block.tail);
      return;
    }
    this.push(`${target} = ${this.lowerValue(block.tail)};`);
  }

  // ------------------------------------------------------------- expressions

  /** True when lowering the expression must emit statements. */
  private static needsStatements(expression: IRExpression): boolean {
    switch (expression.kind) {
      case "if":
        return true;
      case "int-arith":
      case "float-arith":
      case "concat":
      case "equal":
      case "compare":
      case "logical":
        return Emitter.needsStatements(expression.left) || Emitter.needsStatements(expression.right);
      case "int-negate":
      case "float-negate":
      case "not":
        return Emitter.needsStatements(expression.operand);
      case "call":
        return expression.args.some((argument) => Emitter.needsStatements(argument));
      case "interpolate":
        return expression.parts.some((part) => part.kind === "value" && Emitter.needsStatements(part.value));
      case "record":
        return expression.entries.some((entry) => Emitter.needsStatements(entry.value));
      case "variant":
        return expression.args.some((argument) => Emitter.needsStatements(argument));
      case "field":
        return Emitter.needsStatements(expression.target);
      case "match":
        return true;
      default:
        return false;
    }
  }

  /**
   * Lowers operands left to right. If a later operand will emit statements, an
   * earlier one is bound to a temporary so it still evaluates first and once.
   */
  private lowerOperands(expressions: readonly IRExpression[]): string[] {
    const values: string[] = [];
    for (const [index, expression] of expressions.entries()) {
      let value = this.lowerValue(expression);
      const laterEmits = expressions.slice(index + 1).some((later) => Emitter.needsStatements(later));
      if (laterEmits && !IDENTIFIER.test(value)) value = this.bindTemp(value);
      values.push(value);
    }
    return values;
  }

  private lowerValue(expression: IRExpression): string {
    switch (expression.kind) {
      case "int":
        return `${expression.value}n`;
      case "float":
        return floatLiteral(expression.value);
      case "string":
        return JSON.stringify(expression.value);
      case "bool":
        return expression.value ? "true" : "false";
      case "local":
        return jsName(expression.symbol);

      case "call": {
        const args = this.lowerOperands(expression.args).join(", ");
        const target = expression.target;
        const callee = target.origin.kind === "builtin" ? `${RUNTIME}.${target.origin.runtimeName}` : jsName(target);
        return `${callee}(${args})`;
      }

      case "int-arith": {
        const [left, right] = this.lowerOperands([expression.left, expression.right]);
        const helper = INT_HELPERS[expression.operator];
        return `${RUNTIME}.${helper}(${left}, ${right}, ${this.location(expression.span)})`;
      }
      case "int-negate":
        return `${RUNTIME}.ineg(${this.lowerValue(expression.operand)}, ${this.location(expression.span)})`;

      case "float-arith": {
        const [left, right] = this.lowerOperands([expression.left, expression.right]);
        return `(${left} ${expression.operator} ${right})`;
      }
      case "float-negate":
        return `(-${this.lowerValue(expression.operand)})`;

      case "concat": {
        const [left, right] = this.lowerOperands([expression.left, expression.right]);
        return `(${left} + ${right})`;
      }

      case "equal": {
        const [left, right] = this.lowerOperands([expression.left, expression.right]);
        // Strict equality gives exactly the accepted semantics: BigInt for Int,
        // binary64 for Float (NaN unequal to itself, signed zeros equal), and
        // exact non-normalising comparison for String.
        return `(${left} ${expression.negated ? "!==" : "==="} ${right})`;
      }
      case "compare": {
        const [left, right] = this.lowerOperands([expression.left, expression.right]);
        return `(${left} ${expression.operator} ${right})`;
      }

      case "logical":
        return this.lowerLogical(expression);
      case "not":
        return `(!${this.lowerValue(expression.operand)})`;

      case "interpolate": {
        const operands = expression.parts.flatMap((part) => (part.kind === "value" ? [part.value] : []));
        const lowered = this.lowerOperands(operands);
        let next = 0;
        const pieces = expression.parts.map((part) => {
          if (part.kind === "text") return JSON.stringify(part.value);
          const value = lowered[next]!;
          next += 1;
          if (part.value.type.kind === "Int") return `${RUNTIME}.itext(${value})`;
          if (part.value.type.kind === "Float") return `${RUNTIME}.ftext(${value})`;
          return value;
        });
        // The leading "" keeps `+` as string concatenation for every shape.
        return `("" + ${pieces.join(" + ")})`;
      }

      case "record": {
        // Entries are already in source order, and a JavaScript object literal
        // evaluates its property values in written order, so left-to-right
        // evaluation survives without extra machinery.
        const values = this.lowerOperands(expression.entries.map((entry) => entry.value));
        const properties = expression.entries.map((entry, index) => `${fieldKey(entry.field.name)}: ${values[index]!}`);
        return `{ ${properties.join(", ")} }`;
      }
      case "field":
        return `${this.lowerValue(expression.target)}.${fieldKey(expression.field.name)}`;
      case "variant": {
        const payload = expression.variant.payload ?? [];
        const values = this.lowerOperands(expression.args);
        const properties = [`${TAG_KEY}: ${JSON.stringify(expression.variant.name)}`];
        for (const [index, field] of payload.entries()) {
          properties.push(`${fieldKey(field.name)}: ${values[index]!}`);
        }
        return `{ ${properties.join(", ")} }`;
      }

      case "if":
        return this.lowerIfValue(expression);
      case "match":
        return this.lowerMatchValue(expression);
    }
  }

  /**
   * Lowers a match to a chain of tag tests.
   *
   * The scrutinee is bound to a temporary first, because
   * docs/architecture/compiler.md requires a side-effecting operand to run
   * exactly once when a match is lowered. `target` is null when the match is
   * evaluated only for its effects.
   */
  private lowerMatch(expression: Extract<IRExpression, { kind: "match" }>, target: string | null): void {
    const subject = this.bindTemp(this.lowerValue(expression.scrutinee));

    let open = 0;
    for (const arm of expression.arms) {
      if (arm.variant === null) {
        // The catch-all is the final `else`; nothing left to test.
        this.push("} else {");
        this.indent += 1;
        open += 1;
        this.emitArm(arm, subject, target);
        break;
      }
      const test = `${subject}.${TAG_KEY} === ${JSON.stringify(arm.variant.name)}`;
      this.push(open === 0 ? `if (${test}) {` : `} else if (${test}) {`);
      if (open === 0) open = 1;
      this.indent += 1;
      this.emitArm(arm, subject, target);
      this.indent -= 1;
    }
    if (open > 0) this.push("}");
  }

  private emitArm(arm: IRMatch["arms"][number], subject: string, target: string | null): void {
    const payload = arm.variant?.payload ?? [];
    for (const [index, binding] of arm.bindings.entries()) {
      const field = payload[index];
      if (!binding || !field) continue;
      this.push(`const ${jsName(binding)} = ${subject}.${fieldKey(field.name)};`);
    }
    if (target === null) {
      this.emitBranchForEffect(arm.body);
      return;
    }
    this.emitBranchInto(arm.body, target);
  }

  private lowerMatchValue(expression: Extract<IRExpression, { kind: "match" }>): string {
    const temp = this.freshTemp();
    this.push(`let ${temp};`);
    this.lowerMatch(expression, temp);
    return temp;
  }

  private lowerLogical(expression: Extract<IRExpression, { kind: "logical" }>): string {
    if (!Emitter.needsStatements(expression.right)) {
      const left = this.lowerValue(expression.left);
      const right = this.lowerValue(expression.right);
      return `(${left} ${expression.operator} ${right})`;
    }
    // Short-circuiting must survive the hoisting, so the right operand is
    // evaluated inside a guard rather than before the test.
    const left = this.lowerValue(expression.left);
    const temp = this.freshTemp();
    this.push(`let ${temp} = ${left};`);
    this.push(`if (${expression.operator === "&&" ? temp : `!${temp}`}) {`);
    this.indent += 1;
    const right = this.lowerValue(expression.right);
    this.push(`${temp} = ${right};`);
    this.indent -= 1;
    this.push("}");
    return temp;
  }

  private lowerIfValue(expression: Extract<IRExpression, { kind: "if" }>): string {
    const condition = this.lowerValue(expression.condition);
    const temp = this.freshTemp();
    this.push(`let ${temp};`);
    this.push(`if (${condition}) {`);
    this.indent += 1;
    this.emitBranchInto(expression.then, temp);
    this.indent -= 1;
    if (expression.otherwise) {
      this.push("} else {");
      this.indent += 1;
      this.emitBranchInto(expression.otherwise, temp);
      this.indent -= 1;
    }
    this.push("}");
    return temp;
  }
}

function launcher(moduleFileName: string): string {
  // docs/spec/project-structure.md: `main` is invoked by the generated
  // launcher, never as an import side effect.
  return [
    "// Generated by the Koda compiler. Do not edit.",
    `import { main } from "./${moduleFileName}";`,
    'import * as $k from "./koda-runtime.mjs";',
    "",
    "$k.runEntry(main);",
    "",
  ].join("\n");
}

export function emitModule(file: SourceFile, module: IRModule, moduleFileName: string): EmittedModule {
  return {
    moduleSource: new Emitter(file).emitModule(module),
    launcherSource: module.entry ? launcher(moduleFileName) : null,
  };
}
